create table USERS (
user_id INT AUTO_INCREMENT,
user_name VARCHAR(10) NOT NULL,
user_email VARCHAR(50) UNIQUE NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY(user_id)
);

create table SCHEDULES (
schedule_id INT AUTO_INCREMENT,
user_id INT,
schedule_password VARCHAR(10) NOT NULL,
writer VARCHAR(20) NOT NULL,
contents VARCHAR(200) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY(schedule_id),
FOREIGN KEY(user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
);

-- LV 1 전용 테이블
create table N_SCHEDULES (
schedule_id INT AUTO_INCREMENT,
user_name VARCHAR(10) NOT NULL,
schedule_password VARCHAR(10) NOT NULL,
title VARCHAR(20) NOT NULL,
contents VARCHAR(200) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY(schedule_id)
);